### ISSUE TITLE
测试结果问题

### ISSUE THREAD

**Issue by zhou-quan** [LeePleased/StackPropagation-SLU#1]
您好，我在使用process.validate对test数据进行测试的时候，发现save中的测试结果中第二列的标签与原始测试数据中的标签不一致，请问这是什么原因呢？
![截屏2019-11-1416 17 51](https://user-images.githubusercontent.com/30099302/68839929-a5b74c80-06fc-11ea-99e7-66d313810504.png)
![截屏2019-11-1416 19 44](https://user-images.githubusercontent.com/30099302/68839935-aa7c0080-06fc-11ea-9a3e-ce8e9e46de6f.png)

**Comment by LeePleased** [comment]
It seems that these two sentence are not the same, acturally.

**Comment by LeePleased** [comment]
It seems that these two sentence are not the same, acturally.

**Comment by zhou-quan** [comment]
您好，我检查了snips的数据，没有上图一中所示的数据，仅有图二中所示的数据，在输出测试结果时，原测试数据被截断，而且原标签也发生了错位，如图一中的people  B-restaurant_type明显是有问题的。
