### ISSUE TITLE
The Attention may need mask

### ISSUE THREAD

**Issue by HudashiNeo** [LeePleased/StackPropagation-SLU#5]
Hi, The paper team
I have gone through your code in detail, seems that the input tensor of the `forward` function of `SelfAttention` (the main member is a QKVAttention object) class is using padding digits. But in this case, I suppose we also need to put a `mask_tensor`, so that the padding digits will not affect the sentence meaning, right? This may help to improve the performance of the model.

**Comment by HudashiNeo** [comment]
SelfAttention模型貌似缺少mask，因为使用了padding，padding的digits的多少不同，会影响到sentence的Intent和slot吧~ 建议加上哈

**Comment by LeePleased** [comment]
Thanks for your kind mention! We will fix it later.
