### ISSUE TITLE
Prediction slot size does not match sentence size

### ISSUE THREAD

**Issue by viviweipan** [LeePleased/StackPropagation-SLU#6]
When checking the test result on test data of atis, I found 97 size difference of predicted slot and sentence. Details as following, in each tuple I list **(len(w_list), len(r_slot_list), len(p_slot_list))**. So the r_slot_list size is always the same as p_slot_list, but the w_list length can be **shorter or longer.** May I know what causes this? 

**A typical example is the first test result, which has longer prediction than the sentence**
0	i	O	O	atis_flight
1	would	B-depart_date.date_relative	B-depart_date.date_relative	atis_flight
2	like	B-depart_date.day_name	B-depart_date.day_name	atis_flight
3	to	O	O	atis_flight
4	find	O	O	atis_flight
5	a	B-fromloc.city_name	B-fromloc.city_name	atis_flight
6	flight	I-fromloc.city_name	I-fromloc.city_name	atis_flight
7	from	O	O	atis_flight
8	charlotte	B-toloc.city_name	B-toloc.city_name	atis_flight
9	to	O	O	atis_flight
10	las	O	O	atis_flight
11	vegas	O	O	atis_flight
12	that	B-toloc.city_name	B-toloc.city_name	atis_flight
13	makes	B-arrive_time.time_relative	B-arrive_time.time_relative	atis_flight
14	a	B-arrive_time.time	B-arrive_time.time	atis_flight
15	stop	I-arrive_time.time	I-arrive_time.time	atis_flight
16	in	O	O	atis_flight
17	st.	O	O	atis_flight
18	louis	O	O	atis_flight
atis_flight	atis_flight
There is slot error in the prediction:	Yes
**slot diff is [(19, 'B-return_date.day_name', 'B-arrive_date.day_name')]** 

Full list of differences:
[(19, 20, 20), (11, 16, 16), (17, 16, 16), (13, 14, 14), (12, 14, 14), (8, 17, 17), (9, 13, 13), (8, 13, 13), (13, 15, 15), (16, 17, 17), (9, 11, 11), (16, 17, 17), (14, 16, 16), (12, 29, 29), (10, 18, 18), (11, 14, 14), (16, 14, 14), (9, 12, 12), (7, 9, 9), (9, 8, 8), (15, 7, 7), (13, 9, 9), (10, 7, 7), (14, 7, 7), (8, 15, 15), (9, 13, 13), (7, 8, 8), (14, 8, 8), (6, 11, 11), (8, 16, 16), (9, 12, 12), (13, 12, 12), (8, 11, 11), (8, 11, 11), (12, 8, 8), (6, 14, 14), (11, 14, 14), (9, 13, 13), (12, 5, 5), (8, 17, 17), (9, 11, 11), (12, 11, 11), (4, 10, 10), (11, 8, 8), (10, 17, 17), (10, 17, 17), (10, 15, 15), (7, 8, 8), (11, 6, 6), (10, 21, 21), (9, 10, 10), (16, 21, 21), (18, 20, 20), (21, 18, 18), (7, 8, 8), (2, 5, 5), (10, 4, 4), (13, 3, 3), (8, 3, 3), (3, 13, 13), (8, 12, 12), (7, 9, 9), (8, 2, 2), (8, 2, 2), (7, 15, 15), (6, 12, 12), (14, 12, 12), (10, 8, 8), (12, 6, 6), (5, 15, 15), (12, 17, 17), (7, 13, 13), (7, 8, 8), (13, 7, 7), (11, 7, 7), (12, 16, 16), (8, 11, 11), (9, 11, 11), (11, 6, 6), (8, 10, 10), (8, 10, 10), (8, 9, 9), (10, 6, 6), (8, 6, 6), (9, 19, 19), (11, 13, 13), (11, 12, 12), (14, 11, 11), (11, 10, 10), (11, 9, 9), (7, 11, 11), (12, 8, 8), (10, 21, 21), (20, 29, 29), (9, 10, 10), (9, 15, 15), (15, 11, 11)]

**Comment by RaleLee** [comment]
I met the same issue. However, I counted the total number of predict_slots, real_slots and words. And found that they are equal. I went through codes and find the reason. 
Here is why: 
There is a LSTM unit in model. When using **nn.utils.rnn.pack_padded_sequence** and **nn.utils.rnn.pad_packed_sequence**, the data in the batch **needs to be sorted from long to short**. You can find the sorting code in [utils/loader.py add_padding](https://github.com/LeePleased/StackPropagation-SLU/blob/master/utils/loader.py#L365)
However, the writer forgot to **restore the order** after predicting the slot and cause this issue.
So it is not a **principle bug** which may cause the entire results wrong, just a visualization bug~~

I will fix it soon with a PR. : )
